# Archivo .github/workflows/eslint.yml
name: ESLint

on:
  # Ejecuta el workflow en cada push o pull request, pero solo para la rama main
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      # Obtiene el código del repositorio
      - name: Checkout
        uses: actions/checkout@v2

      # Instala Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      # Instala las dependencias de Node.js
      - name: Install dependencies
        run: npm install

      # Ejecuta ESLint
      - name: Run ESLint
        uses: github/super-linter@v4
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_JAVASCRIPT_ES: true
